# Generated by Django 4.2.10 on 2024-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0002_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="headline",
            name="category",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
    ]
